<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackAsTool>true</PackAsTool>
    <ToolCommandName>netrpc</ToolCommandName>
    <Description>.NET tool for generating RPC clients and servers from Thrift IDL</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/AdeAttwood/RpcNet</PackageProjectUrl>
    <RepositoryUrl>https://github.com/AdeAttwood/RpcNet</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/"/>
    <None Include="../../LICENSE" Pack="true" PackagePath="/"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Cli" Version="0.51.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../NetRpc.Core/NetRpc.Core.csproj" />
    <ProjectReference Include="../NetRpc.Lsp/NetRpc.Lsp.csproj" />
  </ItemGroup>

</Project>
