//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from src/ContractForge.ThriftParser/Thrift.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ContractForge.ThriftParser {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IThriftListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ThriftBaseListener : IThriftListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDocument([NotNull] ThriftParser.DocumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDocument([NotNull] ThriftParser.DocumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeader([NotNull] ThriftParser.HeaderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeader([NotNull] ThriftParser.HeaderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinition([NotNull] ThriftParser.DefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinition([NotNull] ThriftParser.DefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.namespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespace([NotNull] ThriftParser.NamespaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.namespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespace([NotNull] ThriftParser.NamespaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.include"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInclude([NotNull] ThriftParser.IncludeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.include"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInclude([NotNull] ThriftParser.IncludeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.struct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct([NotNull] ThriftParser.StructContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.struct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct([NotNull] ThriftParser.StructContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.exceptionStruct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExceptionStruct([NotNull] ThriftParser.ExceptionStructContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.exceptionStruct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExceptionStruct([NotNull] ThriftParser.ExceptionStructContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFields([NotNull] ThriftParser.FieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFields([NotNull] ThriftParser.FieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] ThriftParser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] ThriftParser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.service"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterService([NotNull] ThriftParser.ServiceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.service"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitService([NotNull] ThriftParser.ServiceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.functions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctions([NotNull] ThriftParser.FunctionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.functions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctions([NotNull] ThriftParser.FunctionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.throwsFields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThrowsFields([NotNull] ThriftParser.ThrowsFieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.throwsFields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThrowsFields([NotNull] ThriftParser.ThrowsFieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] ThriftParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] ThriftParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.typedef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedef([NotNull] ThriftParser.TypedefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.typedef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedef([NotNull] ThriftParser.TypedefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.union"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnion([NotNull] ThriftParser.UnionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.union"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnion([NotNull] ThriftParser.UnionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.enum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum([NotNull] ThriftParser.EnumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.enum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum([NotNull] ThriftParser.EnumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.enumValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumValues([NotNull] ThriftParser.EnumValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.enumValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumValues([NotNull] ThriftParser.EnumValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.enumValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumValue([NotNull] ThriftParser.EnumValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.enumValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumValue([NotNull] ThriftParser.EnumValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] ThriftParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] ThriftParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.attributes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttributes([NotNull] ThriftParser.AttributesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.attributes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttributes([NotNull] ThriftParser.AttributesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute([NotNull] ThriftParser.AttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute([NotNull] ThriftParser.AttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] ThriftParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] ThriftParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList([NotNull] ThriftParser.ListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList([NotNull] ThriftParser.ListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.map"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMap([NotNull] ThriftParser.MapContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.map"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMap([NotNull] ThriftParser.MapContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPath([NotNull] ThriftParser.PathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPath([NotNull] ThriftParser.PathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] ThriftParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] ThriftParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.visibility"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVisibility([NotNull] ThriftParser.VisibilityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.visibility"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVisibility([NotNull] ThriftParser.VisibilityContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace ContractForge.ThriftParser
