//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from src/ContractForge.ThriftParser/Thrift.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ContractForge.ThriftParser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ThriftParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IThriftVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDocument([NotNull] ThriftParser.DocumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHeader([NotNull] ThriftParser.HeaderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefinition([NotNull] ThriftParser.DefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace([NotNull] ThriftParser.NamespaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclude([NotNull] ThriftParser.IncludeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct([NotNull] ThriftParser.StructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.exceptionStruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExceptionStruct([NotNull] ThriftParser.ExceptionStructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFields([NotNull] ThriftParser.FieldsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField([NotNull] ThriftParser.FieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.service"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitService([NotNull] ThriftParser.ServiceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctions([NotNull] ThriftParser.FunctionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.throwsFields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrowsFields([NotNull] ThriftParser.ThrowsFieldsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] ThriftParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.typedef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedef([NotNull] ThriftParser.TypedefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.union"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnion([NotNull] ThriftParser.UnionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum([NotNull] ThriftParser.EnumContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.enumValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValues([NotNull] ThriftParser.EnumValuesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.enumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValue([NotNull] ThriftParser.EnumValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] ThriftParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributes([NotNull] ThriftParser.AttributesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] ThriftParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] ThriftParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList([NotNull] ThriftParser.ListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.map"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMap([NotNull] ThriftParser.MapContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPath([NotNull] ThriftParser.PathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] ThriftParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ThriftParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVisibility([NotNull] ThriftParser.VisibilityContext context);
}
} // namespace ContractForge.ThriftParser
