//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from src/NetRpc.ThriftParser/Thrift.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace NetRpc.ThriftParser {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ThriftParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IThriftListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDocument([NotNull] ThriftParser.DocumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDocument([NotNull] ThriftParser.DocumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeader([NotNull] ThriftParser.HeaderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeader([NotNull] ThriftParser.HeaderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinition([NotNull] ThriftParser.DefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinition([NotNull] ThriftParser.DefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespace([NotNull] ThriftParser.NamespaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespace([NotNull] ThriftParser.NamespaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInclude([NotNull] ThriftParser.IncludeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInclude([NotNull] ThriftParser.IncludeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct([NotNull] ThriftParser.StructContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct([NotNull] ThriftParser.StructContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.exceptionStruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExceptionStruct([NotNull] ThriftParser.ExceptionStructContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.exceptionStruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExceptionStruct([NotNull] ThriftParser.ExceptionStructContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFields([NotNull] ThriftParser.FieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFields([NotNull] ThriftParser.FieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField([NotNull] ThriftParser.FieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField([NotNull] ThriftParser.FieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.service"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterService([NotNull] ThriftParser.ServiceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.service"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitService([NotNull] ThriftParser.ServiceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctions([NotNull] ThriftParser.FunctionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctions([NotNull] ThriftParser.FunctionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.throwsFields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThrowsFields([NotNull] ThriftParser.ThrowsFieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.throwsFields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThrowsFields([NotNull] ThriftParser.ThrowsFieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] ThriftParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] ThriftParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.typedef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedef([NotNull] ThriftParser.TypedefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.typedef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedef([NotNull] ThriftParser.TypedefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.union"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnion([NotNull] ThriftParser.UnionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.union"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnion([NotNull] ThriftParser.UnionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnum([NotNull] ThriftParser.EnumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnum([NotNull] ThriftParser.EnumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.enumValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumValues([NotNull] ThriftParser.EnumValuesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.enumValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumValues([NotNull] ThriftParser.EnumValuesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.enumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumValue([NotNull] ThriftParser.EnumValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.enumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumValue([NotNull] ThriftParser.EnumValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] ThriftParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] ThriftParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributes([NotNull] ThriftParser.AttributesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributes([NotNull] ThriftParser.AttributesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute([NotNull] ThriftParser.AttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute([NotNull] ThriftParser.AttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] ThriftParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] ThriftParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] ThriftParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] ThriftParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.map"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMap([NotNull] ThriftParser.MapContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.map"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMap([NotNull] ThriftParser.MapContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPath([NotNull] ThriftParser.PathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPath([NotNull] ThriftParser.PathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] ThriftParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] ThriftParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ThriftParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVisibility([NotNull] ThriftParser.VisibilityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ThriftParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVisibility([NotNull] ThriftParser.VisibilityContext context);
}
} // namespace NetRpc.ThriftParser
